version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: banking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
      POSTGRES_DB: banking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-net

volumes:
  postgres_data:

networks:
  banking-net:
    driver: bridge
